### ISSUE TITLE
Декілька коментів

### ISSUE THREAD

**Issue by lvyyljn** [Hereigo/MentApp#1]
1. Ось такі ДТО найкраще тримати саме в Contracts проекті, щоб не забруднювати контролери,
Можеш зробити папки скажімо Tasks/Categories... і в них розмістити ці дто
https://github.com/Hereigo/MentApp/blob/8d17dcda6ad1320ddf992999dcded7300659280d/WebApi/Controllers/TasksController.cs#L69
2. Також варто використовувати IActionResult як response тип, ось тут https://github.com/Hereigo/MentApp/blob/8d17dcda6ad1320ddf992999dcded7300659280d/WebApi/Controllers/TasksController.cs#L36 
Зараз, якщо айтема немає ти повертаєш просто null i 200 респонс, з IActionResult після перевірки можна буде надіслати 404 респонс, таким чином API стане більш зрозумілим для його консюмера, [docs](https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-8.0)
3. Варто також передавати CancellationToken, просто у Action додати його як параметр і більшість браузерів буде автоматично його попюлейтити, якщо реквест буде довго відбуватись і юзер рефрешне пейджу, запит кенсельнеться (якщо перевіряється IsCancelled)

**Comment by lvyyljn** [comment]
По ось цьому
https://github.com/Hereigo/MentApp/blob/9bf812d125e6b098fd7cb29fd4c0e3fa4cb08d3b/WebApi/Controllers/TasksController.cs#L41
[Ось так](https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-8.0#synchronous-action) можна вертати
return Ok(result)

**Comment by lvyyljn** [comment]
Також інтерфейси репозиторія варто сторити в Data.Abstract, таким чином декаплимо реалізацію і контракт
Бо якщо тримати інтерфейс в Data.EF, тоді ми прив'язуємо цей сервіс саме до EF https://github.com/Hereigo/MentApp/blob/9bf812d125e6b098fd7cb29fd4c0e3fa4cb08d3b/Data.EF/Repositories/ITasksRepository.cs#L5

**Comment by Hereigo** [comment]
Але у нас User : IdentityUser і ми не можемо винести інтерфейс для нього, або ж треба посилатися на Data.EF, а він у свою чергу посилається на Data.Abstract через інтерфейс і виникає "циклічне посилання".

**Comment by lvyyljn** [comment]
Таке уникається додавання доменної моделі
![image](https://github.com/user-attachments/assets/35bf3e8a-fdde-4ae2-994e-2b6f301fbc52)
Ось тут приймати не ATask, який є частино EF, а приймати скажімо ATaskDetails, який буде частиною Domain проекту

Таким чином ми розділимо EF i Domain

**Comment by lvyyljn** [comment]
Це дозволить не лише винести репозиторій у Data.Abstract, а також мати інші назви полів і кастомну модель,
Це дуже корисно у випадку, якщо твоя DB (EF) модель є великою і складною, а тобі потрібна лише її частина, тому створюється її доменна репризентація

**Comment by lvyyljn** [comment]
Обговоримо це на синку нашому ще)
